[package]
name = "academy_core_user_impl"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
academy_cache_contracts.workspace = true
academy_core_auth_contracts.workspace = true
academy_core_oauth2_contracts.workspace = true
academy_core_session_contracts.workspace = true
academy_core_user_contracts.workspace = true
academy_di.workspace = true
academy_email_contracts.workspace = true
academy_models.workspace = true
academy_persistence_contracts.workspace = true
academy_shared_contracts.workspace = true
academy_templates_contracts.workspace = true
academy_utils.workspace = true
anyhow.workspace = true
chrono.workspace = true

[dev-dependencies]
academy_cache_contracts = { workspace = true, features = ["mock"] }
academy_core_auth_contracts = { workspace = true, features = ["mock"] }
academy_core_oauth2_contracts = { workspace = true, features = ["mock"] }
academy_core_session_contracts = { workspace = true, features = ["mock"] }
academy_core_user_contracts = { workspace = true, features = ["mock"] }
academy_demo.workspace = true
academy_email_contracts = { workspace = true, features = ["mock"] }
academy_persistence_contracts = { workspace = true, features = ["mock"] }
academy_shared_contracts = { workspace = true, features = ["mock"] }
pretty_assertions.workspace = true
tokio.workspace = true
